# %%
"""
=================
Process CPMG Data
=================

In this example we demonstrate how to load and EPR spectrum and process the data.

"""
# %%
# Load EPR Data
# -------------
# First, add SpinLab to the Python environment,

import spinlab as sl








# .. ====================
# .. Processing CPMG Data
# .. ====================

# .. Background
# .. ==========
# .. Practically all pulsed EPR sequences are based on the integration of a spin echo for detection. A considerable increase in sensitivity can be achieved by replacing the single echo detection scheme with the sum of echoes generated by a train of echoes. This is shown in the figure below for a two pulse echo sequence.

# .. .. figure:: CPMG_Sequence.png
# ..     :alt: CPMG Sequence

# .. In black, the primary echo is shown, while the refocusing echo train is shown in red. Depending on the specific phases of the pulses, this technique is commonly referred to as Carr-Purcell or Carr-Purcell-Meiboom-Gill (CPMG), named after its inventors [1-5]. The difference between the two sequences is, that CPMG also compensates for pulse imperfections, especially, if the pulse excitation bandwidth is smaller compared to the spectral width, a case commonly encountered in pulsed EPR spectroscopy. This sequence shown in red in the brackets is then repeated N times. Another sequences that performs similar to the CPMG sequence for nonideal pulses is CPMG-2, $/pi/2$(x)- (tau -pi(x)-tau - echo - tau - pi(-x) - tau - echo)N. [6].

# .. In solids, the CPMG echo decay is considerably longer compared to the Hahn-echo decay because the effects of time dependent processes (e.g. spectral diffusion) are minimized [7]. Therefore, the echo can be refocused several times, and the resulting echoes can be summed up to increase the signal-to-noise ratio.

# .. CPMG detection to increase the SNR was first used by Freed et al. [8] and later by Pannier et al. in their first version of the PELDOR/DEER sequence [9].

# .. For an in-depth discussion of the benefits of CPMG detection to increase the SNR please check out the article by |MentinkCPMG|.


# .. Processing in SpinLab
# .. =====================
# .. For this tutorial we assume that all experiments were performed on the |CompactQDEER| spectrometer and that the data file is in the SpecMan4EPR data format.

# .. All processing is done in SpinLab. For this tutorial we will use a data set of a four pulse PELDOR/DEER experiment that was recorded on a ruler molecule. A zip archive including the data set and the SpinLab processing scripts is available **here**.

# .. Load the Data
# .. -------------
# .. We first start with preparing the Python environment.

# .. .. code-block:: python

# ..     import numpy as np
# ..     import matplotlib.pyplot as plt

# ..     import spinlab as sl

# .. Next we will load the experimental data set (here 1888file.exp).

# .. .. code-block:: python

# ..     filename = "../Data/240717/1888file.exp"
# ..     data = sl.load(filename)

# ..     data.coords["t2"] *= 0.4
# ..     data.coords["t"] *= 0.4

# .. For this example, we have to correct the time axis by multiplying it with the dwell time (the time resolution) of the digitizer. You can do a quick check of the data set by printing the content of the spinData object using the print command:

# .. .. code-block:: python

# ..     print(data)
    
# .. This will result in a terminal output similar to the one shown below:

# .. .. code-block:: bash

# ..     values:
# ..             30000 x 126 ndarray (complex128)
# ..     dims:
# ..             ['t2', 't']
# ..     coords:
# ..             array([0.00000e+00, 4.00000e-01, 8.00000e-01, ..., 1.19988e+04,
# ..         1.19992e+04, 1.19996e+04], shape=(30000,))
# ..             array([-4.000e-08, -3.360e-08, -2.720e-08, ...,  7.472e-07,  7.536e-07,
# ..             7.600e-07], shape=(126,))
# ..     attrs:
# ..             'general_version': '1.1'
# ..             'general_demon': '3.6.5'
# ..             'general_name': '4-Pulse DEER CPMG-2'
# ..             'general_dconfig': 'CNIGM0114rev1.cfg'
# ..             'general_pconfig': 'CNIGM0114rev1.cfp'
# ..             +235 attrs

# .. This spinData object has two dimensions labeled *t2* and ``t``, with a size of 30000 complex data point in ``t2`` and 128 points in ``t``.








# .. References
# .. ==========
# .. * [1] T. Vosegaard, F.H. Larsen, H.J. Jakobsen, P.D. Ellis, N.C. Nielsen, Sensitivityenhanced multiple-quantum MAS NMR of half-integer quadrupolar nuclei, J. Am. Chem. Soc. 119 (38) (1997) 9055–9056.
# .. * [2] R. Lefort, J.W. Wiench, M. Pruski, J.-P. Amoureux, Optimization of data acquisition and processing in Carr–Purcell–Meiboom–Gill multiple quantum magic angle spinning nuclear magnetic resonance, J. Chem. Phys. 116 (6) (2002) 2493.
# .. * [3] K.H. Lim, T. Nguyen, T. Mazur, D.E. Wemmer, A. Pines, Sensitivity enhancement in multiple-quantum NMR experiments with CPMG detection, J. Magn. Reson. 157 (1) (2002) 160–162.
# .. * [4] R. Siegel, T.T. Nakashima, R.E. Wasylishen, Signal-to-noise enhancement of NMR spectra of solids using multiple-pulse spin-echo experiments, Concepts Magn. Reson. 26A (2) (2005) 62–77.
# .. * [5] J. Trebosc, J.W. Wiench, S. Huh, V.S.-Y. Lin, M. Pruski, Studies of organically functionalized mesoporous silicas using heteronuclear solid-state correlation NMR spectroscopy under fast magic angle spinning, J. Am. Chem. Soc. 127 (20) (2005) 7587–7593.
# .. * [6] G.A. Álvarez, A. Ajoy, X. Peng, D. Suter, Performance comparison of dynamical decoupling sequences for a qubit in a rapidly fluctuating spin bath, Phys. Rev. A 82 (4) (2010) 042306.
# .. * [7] J.R. Harbridge, S.S. Eaton, G.R. Eaton, Comparison of electron spin relaxation times measured by Carr–Purcell–Meiboom–Gill and two-pulse spin-echo sequences, J. Magn. Reson. 164 (1) (2003) 44–53.
# .. * [8] U. Eliav, J.H. Freed, Multipulse sequences in electron-spin echoes, Rev. Sci. Instrum. 54 (10) (1983) 1416.
# .. * [9] M. Pannier, S. Veit, A. Godt, G. Jeschke, H.W. Spiess, Dead-time free measurement of dipole–dipole interactions between electron spins, J. Magn. Reson. 142 (2) (2000) 331–340.
