# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html


import os
import sys


sys.path.insert(0, os.path.abspath("../../"))
print("path:")
print(sys.path)


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'SpinLab'
copyright = '2025, SpinLab'
author = 'SpinLab Team'
release = '0.1'

from datetime import datetime

date = datetime.now().strftime("%m/%d/%Y, %H:%M:%S")

# The short X.Y version
version_file = "../../spinlab/version.py"
with open(version_file, "r") as f:
    version_code = f.read()
exec(version_code)
version = __version__
release = __version__

print("Build Time: " + date)
print("Version: " + version)
print("Release: " + release)


rst_epilog_list = [
    ("date", date),
    ("author", "The SpinLab Team"),
]


def make_rst_epilog(rst_epilog_list):
    rst_epilog = ""

    for var, value in rst_epilog_list:
        my_string = ".. " + "|" + var + "| replace:: " + value + "\n"

        rst_epilog += my_string

    rst_epilog += "\n"

    return rst_epilog


rst_epilog = make_rst_epilog(rst_epilog_list)

# Add links from linkList.rst
with open("_static/linkList.rst") as f:
    rst_epilog += f.read()


# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.ifconfig",
    "sphinx.ext.intersphinx",
]
#     "sphinx_gallery.gen_gallery",
# ]


autosummary_generate = True  # Turn on sphinx.ext.autosummary

autodoc_member_order = "alphabetical"

exclude_patterns = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "Python"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "links.rst"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# -- Options for Sphinx Gallery output -------------------------------------------------
from sphinx_gallery.sorting import FileNameSortKey

sphinx_gallery_conf = {
    "examples_dirs": "../../examples",  # path to your example scripts
    "gallery_dirs": "auto_examples",  # path to where to save gallery generated output
    "remove_config_comments": True,
    "within_subsection_order": FileNameSortKey,  # Sort by file name
    "run_stale_examples": True,  # Force sphinx to rebuild example. Set to False to only run examples that have changed
}

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    # "analytics_id": "G-917JV2CKD7",  #  Provided by Google in your dashboard
    # 'analytics_anonymize_ip': False,
    # 'prev_next_buttons_location': 'bottom',
    # 'style_external_links': False,
    # 'vcs_pageview_mode': '',
    # 'style_nav_header_background': 'white',
    "logo_only": False,
    # "display_version": False,
    # TOC options
    "sticky_navigation": False,
    "collapse_navigation": True,
    "navigation_depth": 4,
    # 'includehidden': True,
    # 'titles_only': False
    # 'style_nav_header_background': 'white',
    'flyout_display': 'hidden',
    'version_selector': True,
    'language_selector': True,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
# html_static_path = []

def setup(app):
    app.add_css_file("css/rtdSpinLabTtheme.css")


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_logo = "_static/images/SpinLabLogo_300x224.png"


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "Spinlabdoc"


# # -- Options for LaTeX output ------------------------------------------------

# latex_elements = {
#     # The paper size ('letterpaper' or 'a4paper').
#     #
#     # 'papersize': 'letterpaper',
#     # The font size ('10pt', '11pt' or '12pt').
#     #
#     # 'pointsize': '10pt',
#     # Additional stuff for the LaTeX preamble.
#     #
#     # 'preamble': '',
#     # Latex figure (float) alignment
#     #
#     # 'figure_align': 'htbp',
# }

# # Grouping the document tree into LaTeX files. List of tuples
# # (source start file, target name, title,
# #  author, documentclass [howto, manual, or own class]).
# latex_documents = [
#     (master_doc, "Spinlab.tex", "SpinLab Documentation", "Timothy Keller", "manual"),
# ]


# # -- Options for manual page output ------------------------------------------

# # One entry per manual page. List of tuples
# # (source start file, name, description, authors, manual section).
# man_pages = [(master_doc, "Spinlab", "SpinLab Documentation", [author], 1)]


# # -- Options for Texinfo output ----------------------------------------------

# # Grouping the document tree into Texinfo files. List of tuples
# # (source start file, target name, title, author,
# #  dir menu entry, description, category)
# texinfo_documents = [
#     (
#         master_doc,
#         "SpinLab",
#         "SpinLab Documentation",
#         author,
#         "SpinLab",
#         "Bringing the Power of Python to Spin-NMR Spectroscopy",
#         "Miscellaneous",
#     ),
# ]


# # -- Options for Epub output -------------------------------------------------

# # Bibliographic Dublin Core info.
# epub_title = project

# # The unique identifier of the text. This can be a ISBN number
# # or the project homepage.
# #
# # epub_identifier = ''

# # A unique identification for the text.
# #
# # epub_uid = ''

# # A list of files that should not be packed into the epub file.
# epub_exclude_files = ["search.html"]


# # -- Extension configuration -------------------------------------------------
