#DESC	1.2	* DESCRIPTOR INFORMATION
* 
* 
* 	Dataset type and format:
* 
DSRC	EXP
BSEQ	LIT
IKKF	REAL
XTYP	IDX
YTYP	NODATA
ZTYP	NODATA
* 
* 	Item formats:
* 
IRFMT	D
XFMT	D
* 
* 	Data ranges and resolutions:
* 
XPTS	60000
XMIN	3317
XWID	100
* 
* 	Intensity transformation:
* 
* 
* 	Documentational text:
* 
TITL	'Dark roast coffee'
IRNAM	'MW_Absorption'
XNAM	'BField'
IRUNI	''
XUNI	'G'
* 
* ***********************************************************
* 
#SPL	1.2	* STANDARD PARAMETER LAYER
* 
OPER	user
DATE	08/29/23
TIME	21:14:24
CMNT	''
AVGS	1
SPTP	0.002
EXPT	CW
AXS1	B0VL
A1CT	0.3367
A1RS	60000
A1SW	0.01
SANX	0
STMP	305.037357711792
B0VL	0.3367
B0MA	0.0001
B0MF	100000
MWFQ	9458164969.65447
MWPW	0.001
* 
* ***********************************************************
* 
#DSL	1.0	* DEVICE SPECIFIC LAYER
* 
.DVC ESR5000 [11-0225], 1.0

FWV	'FW master: 10.0.6|FW slavemw: 10.1.2|FW slavebf: 10.0.3|FW slaveiq: 10.0.0'
.DVC mwBridge, 1.0

QValue	2051.4248046875
* 
* ***********************************************************
* 
