name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write


# "pip install sphinx-gallery==0.15 && pip install matplotlib==3.7 && pip install numpy==1.24 && pip install scipy==1.10.0 && pip install h5py==3.10.0 && pip install scikit-rf==0.30.0 && h5py==3.10.0"


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser numpy==2.2
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true