name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write


#  sphinx-gallery==0.19 scikit-rf==0.30


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install sphinx==9.0.4 sphinx_rtd_theme==3.1.0 sphinx-gallery==0.20.0 numpy==2.4 scipy==1.16 matplotlib==3.10 h5py==3.16

      - name: Sphinx build
        run: |
          sphinx-build doc _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true